// ============================================================
// TestGenerator — Generates test scripts from recorded actions
// ============================================================

import type { RecordedAction } from "./recorder.js";

export type TestFormat = "typescript" | "python" | "json";

export function generateTestScript(
  actions: RecordedAction[],
  testName: string,
  format: TestFormat,
): string {
  switch (format) {
    case "typescript":
      return generateTypeScript(actions, testName);
    case "python":
      return generatePython(actions, testName);
    case "json":
      return generateJSON(actions, testName);
    default:
      return generateTypeScript(actions, testName);
  }
}

function generateTypeScript(actions: RecordedAction[], testName: string): string {
  const lines: string[] = [
    `// Auto-generated test: ${testName}`,
    `// Generated by mobile-device-mcp test recorder`,
    `// ${new Date().toISOString()}`,
    ``,
    `import { Client } from "@modelcontextprotocol/sdk/client/index.js";`,
    `import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";`,
    ``,
    `async function ${sanitizeName(testName)}() {`,
    `  const transport = new StdioClientTransport({`,
    `    command: "npx",`,
    `    args: ["mobile-device-mcp"],`,
    `  });`,
    `  const client = new Client({ name: "test-runner", version: "1.0.0" });`,
    `  await client.connect(transport);`,
    ``,
    `  try {`,
  ];

  for (let i = 0; i < actions.length; i++) {
    const action = actions[i];
    const paramStr = JSON.stringify(action.params, null, 4).replace(/\n/g, "\n    ");

    lines.push(`    // Step ${i + 1}: ${action.tool}`);
    lines.push(`    const step${i + 1} = await client.callTool({`);
    lines.push(`      name: "${action.tool}",`);
    lines.push(`      arguments: ${paramStr},`);
    lines.push(`    });`);
    lines.push(`    console.log("Step ${i + 1} (${action.tool}):", JSON.stringify(step${i + 1}.content));`);

    // Add delay between interaction actions
    if (isInteractionTool(action.tool) && i < actions.length - 1) {
      lines.push(`    await new Promise(r => setTimeout(r, 1000)); // settle delay`);
    }
    lines.push(``);
  }

  lines.push(`    console.log("Test '${testName}' passed!");`);
  lines.push(`  } finally {`);
  lines.push(`    await client.close();`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`${sanitizeName(testName)}().catch(console.error);`);
  lines.push(``);

  return lines.join("\n");
}

function generatePython(actions: RecordedAction[], testName: string): string {
  const lines: string[] = [
    `# Auto-generated test: ${testName}`,
    `# Generated by mobile-device-mcp test recorder`,
    `# ${new Date().toISOString()}`,
    ``,
    `import asyncio`,
    `import json`,
    `from mcp import ClientSession, StdioServerParameters`,
    `from mcp.client.stdio import stdio_client`,
    ``,
    ``,
    `async def ${sanitizeName(testName)}():`,
    `    server_params = StdioServerParameters(`,
    `        command="npx",`,
    `        args=["mobile-device-mcp"],`,
    `    )`,
    ``,
    `    async with stdio_client(server_params) as (read, write):`,
    `        async with ClientSession(read, write) as session:`,
    `            await session.initialize()`,
    ``,
  ];

  for (let i = 0; i < actions.length; i++) {
    const action = actions[i];
    const paramStr = JSON.stringify(action.params, null, 8);

    lines.push(`            # Step ${i + 1}: ${action.tool}`);
    lines.push(`            step${i + 1} = await session.call_tool(`);
    lines.push(`                "${action.tool}",`);
    lines.push(`                arguments=json.loads('${JSON.stringify(action.params)}'),`);
    lines.push(`            )`);
    lines.push(`            print(f"Step ${i + 1} (${action.tool}): {step${i + 1}.content}")`);

    if (isInteractionTool(action.tool) && i < actions.length - 1) {
      lines.push(`            await asyncio.sleep(1)  # settle delay`);
    }
    lines.push(``);
  }

  lines.push(`            print("Test '${testName}' passed!")`);
  lines.push(``);
  lines.push(``);
  lines.push(`if __name__ == "__main__":`);
  lines.push(`    asyncio.run(${sanitizeName(testName)}())`);
  lines.push(``);

  return lines.join("\n");
}

function generateJSON(actions: RecordedAction[], testName: string): string {
  return JSON.stringify(
    {
      testName,
      generatedAt: new Date().toISOString(),
      generator: "mobile-device-mcp",
      stepCount: actions.length,
      steps: actions.map((a, i) => ({
        step: i + 1,
        tool: a.tool,
        params: a.params,
        durationMs: a.durationMs,
      })),
    },
    null,
    2,
  );
}

function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^(\d)/, "_$1");
}

function isInteractionTool(tool: string): boolean {
  return [
    "tap", "smart_tap", "double_tap", "long_press",
    "swipe", "type_text", "smart_type", "press_key",
  ].includes(tool);
}
