// ============================================================
// License key validation and tier management
// ============================================================

const PREFIX = "[mobile-device-mcp]";

export type LicenseTier = "free" | "pro";

export interface LicenseInfo {
  tier: LicenseTier;
  valid: boolean;
}

/** Tools included in the free tier */
export const FREE_TOOLS = new Set([
  // Device info (3)
  "list_devices",
  "get_device_info",
  "get_screen_size",
  // Screenshots & UI tree (2)
  "take_screenshot",
  "get_ui_elements",
  // Basic interaction (6)
  "tap",
  "double_tap",
  "long_press",
  "swipe",
  "type_text",
  "press_key",
  // Basic app management (2)
  "list_apps",
  "get_current_app",
  // Logs (1)
  "get_logs",
]);

/** Upgrade message shown when a free user calls a pro tool */
export const PRO_UPGRADE_MESSAGE = {
  content: [
    {
      type: "text" as const,
      text: [
        "This is a Pro feature. Upgrade to Pro to unlock all 49 tools.",
        "",
        "Pro includes: AI vision, Flutter inspection, iOS simulator, video recording, test generation, and more.",
        "",
        "Get Pro: https://rzp.io/rzp/r4ijQsJY",
        "",
        "After payment, you'll receive a license key. Add it to your .mcp.json:",
        '  "MOBILE_MCP_LICENSE_KEY": "your-key-here"',
      ].join("\n"),
    },
  ],
  isError: true,
};

/**
 * License key format: MDMCP-XXXXX-XXXXX-XXXXX-CHECK
 *
 * The last segment (CHECK) is a hash of the first 3 segments + a secret salt.
 * This runs offline — no network call needed. Keys are generated by the developer
 * and can't be guessed because the salt is compiled into the binary.
 */
const SALT = "m0b1l3-d3v1c3-mcp-2026-s4r4nsh";

function simpleHash(input: string): string {
  let hash = 0;
  for (let i = 0; i < input.length; i++) {
    const char = input.charCodeAt(i);
    hash = ((hash << 5) - hash + char) | 0;
  }
  // Convert to positive 5-char alphanumeric
  const positive = Math.abs(hash);
  return positive.toString(36).toUpperCase().padStart(5, "0").slice(0, 5);
}

/**
 * Validate a license key offline.
 */
export function validateLicense(): LicenseInfo {
  const key = process.env.MOBILE_MCP_LICENSE_KEY;

  if (!key || key.trim() === "") {
    return { tier: "free", valid: true };
  }

  // Check format: MDMCP-XXXXX-XXXXX-XXXXX-CHECK
  const parts = key.trim().split("-");
  if (parts.length !== 5 || parts[0] !== "MDMCP") {
    return { tier: "free", valid: false };
  }

  const body = parts.slice(0, 4).join("-");
  const expectedCheck = simpleHash(body + SALT);

  if (parts[4] === expectedCheck) {
    return { tier: "pro", valid: true };
  }

  return { tier: "free", valid: false };
}

/**
 * Generate a license key (for internal use — run via: node -e "...")
 * Usage: SALT must match the one compiled in the server.
 */
export function generateLicenseKey(): string {
  const seg = () => Math.random().toString(36).substring(2, 7).toUpperCase();
  const body = `MDMCP-${seg()}-${seg()}-${seg()}`;
  const check = simpleHash(body + SALT);
  return `${body}-${check}`;
}

/** Log the license tier on startup */
export function logLicenseStatus(info: LicenseInfo): void {
  if (info.tier === "pro") {
    process.stderr.write(`${PREFIX} License: Pro (all 49 tools enabled)\n`);
  } else if (!info.valid) {
    process.stderr.write(`${PREFIX} License: Invalid key. Get a valid Pro key at https://rzp.io/rzp/r4ijQsJY\n`);
  } else {
    process.stderr.write(`${PREFIX} License: Free (14 tools — upgrade to Pro for all 49)\n`);
  }
}
